w10d1/tinyapp/config/routes.rb
Rails.application.routes.draw do
  resources :urls
  resources :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "urls#index"
  
  get "/register" => "users#new"
  post "/users" => "users#create"


  get "/login" => "sessions#new"
  get "/logout" => "sessions#destroy"
  post "/login" => "sessions#create"

end

w10d1/tinyapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

w10d1/tinyapp/app/models/url.rb
class Url < ApplicationRecord
  belongs_to :user
end

w10d1/tinyapp/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :urls
end

w10d1/tinyapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize

    redirect_to "/login" unless current_user
  end



end




# bob = value ? value : nil

w10d1/tinyapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.

      respond_to do |format|
        session[:user_id] = user.id
        if user.save
          format.html { redirect_to "/" }
          format.json { render :show, status: :created, location: user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: user.errors, status: :unprocessable_entity }
        end
      end
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end


# app.use((req,res,next) => {
#   if(whitelist.includes(req.url)){
#     next()
#   }

#   redirect("/")
# })

w10d1/tinyapp/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]

  before_action :authorize
  skip_before_action :verify_authenticity_token
  # GET /urls or /urls.json
  def index
    # @urls = Url.all
    # SELECT * FROM urls

    @user = current_user
    @urls = @user.urls.all
    # SELECT * FROM urls WHERE user_id = $1


  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @user = current_user
    @url = @user.urls.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @user = current_user

    new_url = {
      :user_id => @user.id,
      :description => url_params[:description],
      :long_url => url_params[:long_url],
      :short_url => SecureRandom.alphanumeric(6)
    }

    @url = @user.urls.new(new_url)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_url(@url), notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to url_url(@url), notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:long_url, :description)
    end
end

w10d1/tinyapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

w10d1/tinyapp/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d1/tinyapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

w10d1/tinyapp/app/helpers/urls_helper.rb
module UrlsHelper
end

w10d1/tinyapp/app/helpers/users_helper.rb
module UsersHelper
end

w10d1/tinyapp/app/views/application/_header.html.erb
<header class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
  <h1 class="navbar-brand">Tinyapp!</h1>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <% if current_user %>
      <li class="nav-item">
        <%= link_to "Logout", "/logout" %>          
      </li>
      <li class="nav-item">
      <h2>Logged in as : <%= current_user.name%></h2>
        
      </li>
  <% else %>
      <li class="nav-item">      
    <%= link_to "Login", "/login" %>
      </li>
      <li class="nav-item">       
    <%= link_to "Register", "/register" %>
      </li>
  <% end %>
  </ul>
  </div>
</div>
</header>

w10d1/tinyapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "header" %>
    <%= yield %>
  </body>
</html>

w10d1/tinyapp/app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :long_url, style: "display: block" %>
    <%= form.text_field :long_url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

w10d1/tinyapp/app/views/urls/_url.html.erb
<tr id="<%= dom_id url %>">
  <td>
    <a href="<%= url.long_url %>" target="_blank">
    <%= url.short_url %>
    </a>
  </td>

  <td>
    <%= url.long_url %>
  </td>

  <td>
    <%= url.description %>
  </td>

  <td>
      <%= link_to "View & Edit", url %>
  </td>




</div>

w10d1/tinyapp/app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

w10d1/tinyapp/app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Urls</h1>

<table class="table">
      <thead>
        <tr>
          <th scope="col">Short URL</th>
          <th scope="col">Long URL</th>
          <th scope="col">Description</th>
          <th scope="col">View and Edit</th>
        </tr>
      </thead>
      <tbody>

  <% @urls.each do |url| %>
    <%= render url %>

  <% end %>

      </tbody>
    </table>

<%= link_to "New url", new_url_path %>

w10d1/tinyapp/app/views/urls/new.html.erb
<h1>New url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Back to urls", urls_path %>
</div>

w10d1/tinyapp/app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @url %>

<div>
  <%= link_to "Edit this url", edit_url_path(@url) %> |
  <%= link_to "Back to urls", urls_path %>

  <%= button_to "Destroy this url", @url, method: :delete %>
</div>

w10d1/tinyapp/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

w10d1/tinyapp/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

w10d1/tinyapp/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

w10d1/tinyapp/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

w10d1/tinyapp/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

w10d1/tinyapp/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>